name: Esteira de CI

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12']
    steps:
      - uses: actions/checkout@v4

      - name: Setup do Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Instalando dependencias
        run: |
          python -m pip install --upgrade pip
          pip install black pre-commit

      - name: Executa pre-commit
        run: pre-commit run --all-files

      - name: Black check
        run: black --check .
